### PR TITLE
get cmb2 group params into shortcode

### PR DESCRIPTION
**Pull request by modemlooper**
- added a check to see if cmb2 data is an object and then  convert to shortcode attribute

### CODE REVIEW

**Comment by jtsternberg** [comment]
This seems sane, but would like to know the scenario where it is desired/necessary.

**Comment by modemlooper** [comment]
when you have a select and you want to show a group of fields based on select.

**Comment by jtsternberg** [comment]
Was hoping for some pseudo-code to demonstrate. You mean like:
`$options = array( 'all', 'this', 'that' );`
and selecting 'all' should output: `[shortcode this=1 that=1]`?

**Comment by modemlooper** [comment]
Thats a good use case, my use case now is select option then only display this group or fields

**Comment by jtsternberg** [comment]
(For onlookers) we discussed this a bit more and determined that it's better, in most cases, to use the filter to modify shortcode attributes before they are sent back to JS: https://github.com/jtsternberg/Shortcode_Button/blob/master/shortcode-button.php#L348-L362

**Pull request closed without merging**
